"""ReportLab styles, typography, and page canvas."""

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas

# Color Palette
PRIMARY_COLOR = HexColor("#0f172a")     # Deep Slate
SECONDARY_COLOR = HexColor("#475569")   # Muted Slate
USER_ACCENT = HexColor("#1d4ed8")       # Vibrant Blue
ASSISTANT_ACCENT = HexColor("#0f766e")  # Teal Slate
BG_USER = HexColor("#eff6ff")           # Light Blue Tint
BG_ASSISTANT = HexColor("#f8fafc")      # Very Light Gray Tint
BG_CODE = HexColor("#f1f5f9")           # Code Block Slate
BORDER_CODE = HexColor("#cbd5e1")       # Border Slate
TEXT_DARK = HexColor("#1e293b")         # Charcoal Body Text
BORDER_LIGHT = HexColor("#e2e8f0")      # Divider/Border


class NumberedCanvas(canvas.Canvas):
    """Canvas that computes total page count dynamically for 'Page X of Y' footers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(SECONDARY_COLOR)

        page_w, page_h = letter
        margin = 40

        # Header rule and title on pages > 1
        if self._pageNumber > 1:
            self.setStrokeColor(BORDER_LIGHT)
            self.setLineWidth(0.5)
            self.line(margin, page_h - 35, page_w - margin, page_h - 35)
            self.drawString(margin, page_h - 30, "AI Conversation")

        # Footer
        self.setStrokeColor(BORDER_LIGHT)
        self.setLineWidth(0.5)
        self.line(margin, 40, page_w - margin, 40)

        # Footer Left: Brand
        self.drawString(margin, 28, "Generated by AI Conversation CLI")

        # Footer Right: Page X of Y
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(page_w - margin, 28, page_str)

        self.restoreState()


def get_pdf_styles():
    """Create and return custom typography stylesheet."""
    styles = getSampleStyleSheet()

    # Document Header Title
    styles.add(
        ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=PRIMARY_COLOR,
            spaceAfter=6,
        )
    )

    # Document Subtitle / Metadata
    styles.add(
        ParagraphStyle(
            "DocMeta",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=SECONDARY_COLOR,
            spaceAfter=14,
        )
    )

    # User Header
    styles.add(
        ParagraphStyle(
            "UserBadge",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=USER_ACCENT,
            spaceBefore=10,
            spaceAfter=4,
        )
    )

    # Assistant Header
    styles.add(
        ParagraphStyle(
            "AssistantBadge",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=ASSISTANT_ACCENT,
            spaceBefore=12,
            spaceAfter=4,
        )
    )

    # Regular Body Paragraph
    styles.add(
        ParagraphStyle(
            "ConvBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=TEXT_DARK,
            spaceAfter=6,
        )
    )

    # Heading 1 inside message
    styles.add(
        ParagraphStyle(
            "ConvH1",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=PRIMARY_COLOR,
            spaceBefore=8,
            spaceAfter=4,
        )
    )

    # Heading 2 inside message
    styles.add(
        ParagraphStyle(
            "ConvH2",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=PRIMARY_COLOR,
            spaceBefore=6,
            spaceAfter=3,
        )
    )

    # List item
    styles.add(
        ParagraphStyle(
            "ConvList",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=TEXT_DARK,
            leftIndent=14,
            spaceAfter=3,
        )
    )

    # Code snippet inside box
    styles.add(
        ParagraphStyle(
            "ConvCode",
            parent=styles["Normal"],
            fontName="Courier",
            fontSize=8.5,
            leading=11,
            textColor=HexColor("#1e293b"),
        )
    )

    # Table cell text
    styles.add(
        ParagraphStyle(
            "ConvTableCell",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=TEXT_DARK,
        )
    )

    # Table header cell text
    styles.add(
        ParagraphStyle(
            "ConvTableHead",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=PRIMARY_COLOR,
        )
    )

    return styles
